services:
  postgres:
    image: postgres:16
    container_name: payment-routing-engine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payment_routing_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: